### ISSUE TITLE
"unable to agree on a pubkey algorithm"

### ISSUE THREAD

**Issue by r2evans** [RainMark/oxfs#24]
I'm not certain that the pubkey algorithm is the only issue here, but the uncaught exception coming out before asking for the password and failing immediately after it suggests I need to start there. Error message below. When prompted, I paste in the password (from my password manager). I verified that `ssh -p remport remuser@remipaddr` works without issue.

Versions: oxfs-0.5.5 and paramiko-3.5.0 (in the venv, installed per the install docs). Running on macos 15.1.1.

```bash
(oxfs) locuser@mac ~ % .venv/oxfs/bin/oxfs -v --host remuser@remipaddr --ssh-port remport --remote-path=rempath --mount-point=/Users/locuser/locpath  --cache-path=/Users/locuser/.oxfs --auto-cache
[2024-12-07 09:36:51,093][INFO][transport.py -- _log():1944][Connected (version 2.0, client OpenSSH_9.6p1)]
[2024-12-07 09:36:51,333][ERROR][transport.py -- _log():1944][Exception (client): Unable to agree on a pubkey algorithm for signing a 'ssh-rsa' key!]
[2024-12-07 09:36:51,338][ERROR][transport.py -- _log():1942][Traceback (most recent call last):]
[2024-12-07 09:36:51,338][ERROR][transport.py -- _log():1942][  File "/Users/locuser/.venv/oxfs/lib/python3.13/site-packages/paramiko/transport.py", line 2262, in run]
[2024-12-07 09:36:51,338][ERROR][transport.py -- _log():1942][    handler(m)]
[2024-12-07 09:36:51,339][ERROR][transport.py -- _log():1942][    ~~~~~~~^^^]
[2024-12-07 09:36:51,339][ERROR][transport.py -- _log():1942][  File "/Users/locuser/.venv/oxfs/lib/python3.13/site-packages/paramiko/auth_handler.py", line 395, in _parse_service_accept]
[2024-12-07 09:36:51,339][ERROR][transport.py -- _log():1942][    algorithm = self._finalize_pubkey_algorithm(key_type)]
[2024-12-07 09:36:51,339][ERROR][transport.py -- _log():1942][  File "/Users/locuser/.venv/oxfs/lib/python3.13/site-packages/paramiko/auth_handler.py", line 368, in _finalize_pubkey_algorithm]
[2024-12-07 09:36:51,339][ERROR][transport.py -- _log():1942][    raise AuthenticationException(err.format(key_type))]
[2024-12-07 09:36:51,339][ERROR][transport.py -- _log():1942][paramiko.ssh_exception.AuthenticationException: Unable to agree on a pubkey algorithm for signing a 'ssh-rsa' key!]
[2024-12-07 09:36:51,339][ERROR][transport.py -- _log():1942][]
remuser@remipaddr's password:
[2024-12-07 09:36:52,405][INFO][transport.py -- _log():1944][Connected (version 2.0, client OpenSSH_9.6p1)]
[2024-12-07 09:36:52,648][ERROR][transport.py -- _log():1944][Exception (client): Unable to agree on a pubkey algorithm for signing a 'ssh-rsa' key!]
[2024-12-07 09:36:52,650][ERROR][transport.py -- _log():1942][Traceback (most recent call last):]
[2024-12-07 09:36:52,650][ERROR][transport.py -- _log():1942][  File "/Users/locuser/.venv/oxfs/lib/python3.13/site-packages/paramiko/transport.py", line 2262, in run]
[2024-12-07 09:36:52,651][ERROR][transport.py -- _log():1942][    handler(m)]
[2024-12-07 09:36:52,651][ERROR][transport.py -- _log():1942][    ~~~~~~~^^^]
[2024-12-07 09:36:52,651][ERROR][transport.py -- _log():1942][  File "/Users/locuser/.venv/oxfs/lib/python3.13/site-packages/paramiko/auth_handler.py", line 395, in _parse_service_accept]
[2024-12-07 09:36:52,651][ERROR][transport.py -- _log():1942][    algorithm = self._finalize_pubkey_algorithm(key_type)]
[2024-12-07 09:36:52,651][ERROR][transport.py -- _log():1942][  File "/Users/locuser/.venv/oxfs/lib/python3.13/site-packages/paramiko/auth_handler.py", line 368, in _finalize_pubkey_algorithm]
[2024-12-07 09:36:52,651][ERROR][transport.py -- _log():1942][    raise AuthenticationException(err.format(key_type))]
[2024-12-07 09:36:52,651][ERROR][transport.py -- _log():1942][paramiko.ssh_exception.AuthenticationException: Unable to agree on a pubkey algorithm for signing a 'ssh-rsa' key!]
[2024-12-07 09:36:52,651][ERROR][transport.py -- _log():1942][]
Permission denied.
[2024-12-07 09:36:52,652][ERROR][oxfs.py -- try_connect():92][No existing session]
Traceback (most recent call last):
  File "/Users/locuser/.venv/oxfs/lib/python3.13/site-packages/oxfs/oxfs.py", line 86, in try_connect
    client.connect(self.host, port=self.port, disabled_algorithms=dict(pubkeys=["rsa-sha2-512", "rsa-sha2-256"]),
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                   username=self.user, password=password, key_filename=self.key_filename)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/locuser/.venv/oxfs/lib/python3.13/site-packages/paramiko/client.py", line 485, in connect
    self._auth(
    ~~~~~~~~~~^
        username,
        ^^^^^^^^^
    ...<9 lines>...
        passphrase,
        ^^^^^^^^^^^
    )
    ^
  File "/Users/locuser/.venv/oxfs/lib/python3.13/site-packages/paramiko/client.py", line 818, in _auth
    raise saved_exception
  File "/Users/locuser/.venv/oxfs/lib/python3.13/site-packages/paramiko/client.py", line 805, in _auth
    self._transport.auth_password(username, password)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/Users/locuser/.venv/oxfs/lib/python3.13/site-packages/paramiko/transport.py", line 1627, in auth_password
    raise SSHException("No existing session")
paramiko.ssh_exception.SSHException: No existing session
```

**Comment by RainMark** [comment]
due to paramiko's bugs, pubkeys=["rsa-sha2-512", "rsa-sha2-256"] is not allow. you can try ssh-ed25519
